name: Build and Upload Go Project

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Build
        run: |
          chmod +x ./Make.sh
          ./Make.sh

      - name: Print
        run: |
          ls
        
      - name: Prepare files for upload
        run: |
          chmod +x ./bin/*
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: ${{ github.event.inputs.tag_name }}
          draft: false
          prerelease: false

      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          find bin -type f -name "*.gz" -print0 | while IFS= read -r -d '' file; do
            echo "Uploading $file..."
            gh bin upload ${{ github.event.inputs.tag_name }} "$file"
          done
